### ISSUE TITLE
Build fails - Cannot find module 'unicode/category/So'

### ISSUE THREAD

**Issue by halhenke** [relax/relax#114]
I understand the grunt-cli issue is already known but getting past that `npm run build` eventually fails for me with:

```
Running "browserify:production" (browserify) task
>> Bundle public/js/public.js created.
>> Error: Cannot find module 'unicode/category/So' from '/Users/hal/code/relax/relax/node_modules/slug'
Warning: Error running grunt-browserify. Use --force to continue.
```

**Comment by bruno12mota** [comment]
Have you tried ```npm i && npm run dev```? Does it fail the same?

**Comment by magalhas** [comment]
@halhenke that looks like an interrupted or failed `npm install`. Please make sure you have all the dependencies met. Check [https://github.com/relax/relax#dependencies](here).

**Comment by halhenke** [comment]
actually yeah `npm install` was bailing out with this error before the build script continued - 

```
> fsevents@0.3.8 install /Users/hal/code/Web/relax/relax/node_modules/express-react-engine/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
/Users/hal/code/Web/relax/relax/node_modules/.bin/touch: line 1: syntax error near unexpected token `('
/Users/hal/code/Web/relax/relax/node_modules/.bin/touch: line 1: `var touch = require("../touch")'
make: *** [Release/obj.target/fse/fsevents.o] Error 2
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hal/code/Web/relax/relax/node_modules/express-react-engine/node_modules/fsevents
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:fsevents@0.3.8 fsevents@0.3.8 install: `node-gyp rebuild`
npm WARN install:fsevents@0.3.8 Exit status 1
```

**Comment by magalhas** [comment]
Can you try with iojs-v2 instead of node-v4?

**Comment by PatrickSCLin** [comment]
I occurred same issue!

**Comment by magalhas** [comment]
@PatrickSCLin were you able to solve it?

**Comment by PatrickSCLin** [comment]
each of libraries install from outside of relax is fine, but shown errors when I was in root of relax

I just execute npm install sharp from outside and replace into node_componenets of relax, then execute npm start, it's able to execute npm start

still get some errors if I try to use npm run dev, 

my env is node 4.2.1, npm 3.3.9, libvips 7.38.5 


root@Server:~/relax# npm run dev

> relax@1.0.0 dev /root/relax
> grunt dev

Running "less:development" (less) task
File public/css/main.css created

Running "browserify:common" (browserify) task
>> Bundle public/js/common.js created.

Running "browserify:development" (browserify) task
>> Bundle public/js/admin.js created.
>> Bundle public/js/auth.js created.
>> Bundle public/js/public.js created.

Running "copy:main" (copy) task
Created 3 directories, copied 1 file

Running "concurrent:dev" (concurrent) task
    Running "watch" task
    Waiting...
    Running "nodemon:dev" (nodemon) task
    [nodemon] v1.3.8
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    [nodemon] starting `node index.js dev`
    Fatal error: spawn ENOMEM
    Tue, 27 Oct 2015 10:28:31 GMT express-session deprecated undefined resave option; provide resave option at lib/server/index.js:75:41
    Tue, 27 Oct 2015 10:28:31 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at lib/server/index.js:75:41
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
    
    <--- Last few GCs --->
    
       76262 ms: Mark-sweep 67.9 (32144.7) -> 65.0 (32207.7) MB, 157.4 / 0 ms [allocation failure] [GC in old space requested].
       76440 ms: Mark-sweep 65.0 (32221.3) -> 65.0 (32344.3) MB, 176.5 / 0 ms [allocation failure] [GC in old space requested].
       76611 ms: Mark-sweep 65.0 (32358.0) -> 63.6 (32475.0) MB, 170.4 / 0 ms [last resort gc].
       76711 ms: Mark-sweep 63.6 (32475.0) -> 61.2 (32586.0) MB, 99.7 / 0 ms [last resort gc].
    
    
    <--- JS stacktrace --->
    
    ==== JS stack trace =========================================
    
    Security context: 0x13a196f36ae1 <JS Object>
        1: Join(aka Join) [native array.js:154] [pc=0x2f4daa2874b8] (this=0x13a196f04131 <undefined>,o=0x63709dd06d1 <JS Array[478]>,v=478,C=0x33fb065ff571 <String[4]\: ,\n  >,B=0x1c6dbe2617a1 <JS Function ConvertToString (SharedFunctionInfo 0x13a196f50e41)>)
        2: InnerArrayJoin(aka InnerArrayJoin) [native array.js:331] [pc=0x2f4daa28632a] (this=0x13a196f04131 <undefined>,C=0x33fb065ff571 <String...
    
Warning: Tue, 27 Oct 2015 10:28:31 GMT express-session deprecated undefined resave option; provide resave option at lib/server/index.js:75:41
Tue, 27 Oct 2015 10:28:31 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at lib/server/index.js:75:41
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 3.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! relax@1.0.0 dev: `grunt dev`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the relax@1.0.0 dev script 'grunt dev'.
npm ERR! This is most likely a problem with the relax package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls relax
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/relax/npm-debug.log
root@Server:~/relax#

**Comment by bruno12mota** [comment]
Seems like it goes out of memory. I tried using npm 3 and latest node version a while back and it gave me a lot of problems, since some libs still don't support it. Try using npm 2^ and io.js v2^ it's what we're using and goes great, if it still errors out let us know

**Comment by magalhas** [comment]
We should probably state this in the README until we've got it solved.

**Comment by starzou** [comment]
Hi all, I use iojs v3.3.1, run npm i -dd.
Error Message:
```bash  
npm verb cache add spec event-stream@~0.5
npm verb addNamed ">=0.5.0 <0.6.0" is a valid semver range for event-stream
npm verb addNameRange registry:https://registry.npmjs.org/event-stream not in flight; fetching
npm info linkStuff is-npm@1.0.0
npm verb readDependencies loading dependencies from /root/relax/node_modules/nodemon/node_modules/update-notifier/node_modules/string-length/package.json
npm verb readDependencies loading dependencies from /root/relax/node_modules/grunt-concurrent/node_modules/pad-stream/node_modules/meow/node_modules/normalize-package-data/node_modules/is-builtin-module/package.json
npm verb write writing to /root/relax/node_modules/grunt-contrib-uglify/node_modules/maxmin/node_modules/gzip-size/node_modules/browserify-zlib/package.json
 
> buffertools@2.1.3 install /root/relax/node_modules/slug/node_modules/unicode/node_modules/bufferstream/node_modules/buffertools
> node-gyp rebuild


Killed
```

I'm sure that If the user or sysadmin did not kill the program the kernel may have. The kernel would only kill a process under exceptional circumstances such as extreme resource starvation (think mem+swap exhaustion).

**Comment by bruno12mota** [comment]
You should be able to use node 4 from now on

**Comment by xiajian** [comment]
`npm install unicode`, then fix this issue.
