### ISSUE TITLE
Styles overrides according to viewport

### ISSUE THREAD

**Issue by magalhas** [relax/relax#143]

**Comment by bruno12mota** [comment]
How should this be handled if I change a style property when on a different display?

I think what makes more sense is, by changing a property of a style it will save to that style according to the current viewport. So that every element with that style when the viewport changes matches the custom changes made in that style for that viewport. Will be a though one though.

**Comment by magalhas** [comment]
We've just discussed this. I agree that the change should be persisted next to the style.
