### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mzgnr** [relax/relax#211]
Hi,

Thanks for your work. It looks amazing :smiley:  I would like to contribute to project(maybe part-time) but I've not seen any roadmap. Can you publish a roadmap for beta or stable version ?

**Comment by magalhas** [comment]
Hi @mzgnr, thank you for your interest. We actually have a road map that has been kept private until now. I'll talk with @bruno12mota so that we can share it here on GitHub. Anyway, everything that we intend to do for the beta release is already created as issues part of 0.1.0 milestone.

**Comment by bruno12mota** [comment]
Hey @mzgnr we're currently working on a dashboard redesign on this branch https://github.com/relax/relax/tree/dashboard-redesign. As to the roadmap as @magalhas said we have the issues for 0.1.0 milestone, we'll create a ROADMAP.md on the repo soon so everyone can see an overview of what is missing :smile:

**Comment by mzgnr** [comment]
Hey @bruno12mota , thanks for the reply. I checked the issues for 0.1.0 milestone it looks okay. I'm experiencing some build, run issues both master and dashboard-redesing branches. I' trying to fix the issues. I think your folder structure is really confusing and complex and there are something wrong with the babel stuff. Webpack can not build some assets for some reason. And if there are no specific reasons  for choosing less, would you rather choose sass , postcss or rucksack ?

**Comment by bruno12mota** [comment]
Hi @mzgnr. 

As to the build issues, which version of node are you running? Try with latest 4. Also for now run only 'npm run dev', specially on the dashboard-redesign branch since the production scripts aren't yet made.

As to the folder structure, I've changed it for dashboards-redesign, I'm now following a recursive structure you can see how this works here for example: https://gist.github.com/ryanflorence/110d4538bf98694538de by @ryanflorence. The old simpler structure wasn't scaling that well, and for this complexity there is the need for a better structure.

I use less because it's what I'm used to work with. It's pretty much the same as sass and we basically only use it for some variables

**Comment by mzgnr** [comment]
Thanks I get the idea. I think it would be better if there were dist, src & webpack folders on top of the project.

**Comment by bruno12mota** [comment]
On the dashboard-redesign branch there is already a webpack folder with the node and the client builds config, it's still work in progress. The src folder you mentioned is the lib folder, the same with a different name. Any doubt you have shoot :smile: 

Will keep this open, @magalhas is making the Roadmap.

**Comment by mzgnr** [comment]
@bruno12mota thanks for the reply. I knew that lib folder is the src folder i mentioned. Generally my react workflow has a folder/file structure that includes both js and scss. But yours is also good. Maybe im a little insistent about the roadmap and understanding the core api because i like the project and i want to understand its core api and contribute to project. I actually want to work on the project and speed up the development process :smiley: 

You said dashboard-redesign branch's production scripts were not ready yet. Is there anything i can do about it ? I want to work on that branch and work on it for the roadmap.

**Comment by magalhas** [comment]
Hey @mzgnr we've published an "initial draft" (probably it won't be edited anytime soon) of the roadmap in [here](https://github.com/relax/relax/blob/master/ROADMAP.md).

It lacks details for each feature because we couldn't find the time, but if you want any detail on anything please comment the respective issues.

There are some issues still yet to be created, if that's the case feel free to create them so that we can share with you what we have in mind.

**Comment by bruno12mota** [comment]
@mzgnr no problem in being insistent, glad you like the project and would be great to have some contributors :smile: 

Working on the production build would be great. Basically is handling the package json scripts and the babel configs, if you could pick that up would be awesome and of course if you have any more doubt feel free to shoot

**Comment by gustavorino** [comment]
Hi everyone!

Have you ever tried to run Relax on Windows?
 
i've tried that today and wasn't wasn't successfully. After editing all npm tasks and fixing babel related problems, i was able to create an user but once i logged-in the server halted.

On Mac everything went smooth, it would be great if Relax were able to run on both systems out of the box.

Great project, hope to contribute soon.

**Comment by magalhas** [comment]
Hi @gustavorino,

We currently have some problems with the installation, we've got some git dependencies that we need to get rid of to have a faster installation.

Regarding Windows support that's something we're definitely going to look into for our first beta release but it's not on the top of our priorities.

Can you let us what fixes did you have to apply to our babel configuration? The server halting is very strange, I don't think we ever had reports of such an issue in the past.

**Comment by bruno12mota** [comment]
Roadmap is available at https://github.com/relax/relax/blob/master/ROADMAP.md
