### ISSUE TITLE
Question about Apollo Client

### ISSUE THREAD

**Issue by stubailo** [relax/relax#228]
Hi! I'm working on Apollo Client, which I'm hoping will soon be the most straightforward way to use Redux with GraphQL. Would you mind taking a quick look and telling me about your initial impressions?

Here's the repo: https://github.com/apollostack/apollo-client

Here are the docs: http://docs.apollostack.com/apollo-client/index.html

We're still building up some core features around pagination, optimistic UI, fragment composition, etc. Would be really interested to know which of those features would be important to a project like this, and maybe work together to make them happen!

**Comment by bruno12mota** [comment]
Hey @stubailo looks like an awesome project, great to see new stuff around this 😄  

Took a look through the docs and it seems to have a close approach to what I did with Relate http://relax.github.io/relate/ which is what I've been using in Relax. 

They have some differences between them, in Relate I define fragments with normal json objects, so that people can define them and handle them between components as they see fit. One thing I've done with Relate that has been really helpful is providing a way to intersect queries in other places in the reducer. This allows me to mutate them locally freely.

I see apollo client has already a caching mechanism, which relate doesn't have, it's overall a more advanced and mature lib.

I believe in apollo you don't have a way to define and merge fragments between components right? Like relay does. Or in relate http://relax.github.io/relate/fragments.html 

Also is apollo schema agnostic as well? How does it handle the data and additions to lists of nodes for example?

**Comment by smolinari** [comment]
Great conversation. I am making myself known with this post, so I am certain not to miss any replies. :smile: 

Scott

**Comment by delgermurun** [comment]
@smolinari There is subscribe button on right sidebar.

**Comment by smolinari** [comment]
Oh Duh! If it were snake, it would have bitten me. LOL!

Scott

**Comment by stubailo** [comment]
@bruno12mota wow, didn't see Relate! That looks really awesome.

The "Why Relate?" section is very similar to the hypothetical "Why Apollo Client?" section we have yet to write. The most similar thing we have our design doc, which also lists the features we are looking to build: https://github.com/apollostack/apollo-client/blob/master/design.md

I think the planned features include basically everything in your "It loses some capabilities over Relay that can be worked out eventually:" section. We're hoping to address those within the next month for sure.

#### JSON queries vs. strings

I agree that using JSON for the fragments/queries is a lot more convenient from certain points of view - for example, it's much more obvious how to manipulate them in user code. However, there are a few critical drawbacks:

1. You can't statically analyze the queries for errors. We're working on a tool that looks for tagged template strings in your code, and tells you where there might be typos in your queries: https://github.com/apollostack/eslint-plugin-graphql When we talked to people currently using GraphQL, this was one of their favorite features of Relay.
2. The underlying format isn't the standard GraphQL AST, which means future tools build against that AST won't work here. For example, I was going to build something to do the fragment merging for the AST, and ideally other libraries will be able to use that as well. I think GraphQL-JS is a great intersection point for all of the different libraries.
3. You need separate documentation for how to use the JSON format - it's not a huge deal, but it would be great if it was "just GraphQL" in the sense that you could copy a string from GraphiQL into your code.

I wonder what your thoughts are about this - I've found that the GraphQL AST is not so hard to work with directly, thanks to tools like: https://astexplorer.net/

#### Answering questions

Let me just run through the questions in your comment:

> I believe in apollo you don't have a way to define and merge fragments between components right?

Not yet, I'm planning on working on that this week and early next. It's one of the biggest missing features.

> Also is apollo schema agnostic as well?

Yes, right now it doesn't assume anything about your schema. Our plan is to add the ability to plug in various schema-specific functionality, for example:


1. Normalizing objects by `id`
2. Pagination using Relay Connections and custom setups with page numbers
3. Client-side sorting

We think of Apollo Client as almost a set of utilities to build the GraphQL client you want, rather than something opinionated to a specific schema or approach to pagination, etc.

> How does it handle the data and additions to lists of nodes for example?

Right now, the cache is normalized, but since it doesn't interpret Node IDs by default you mostly end up with per-query caching. So, with some examples:

```
// First query this
{
  user(id: 5) {
    firstName
    lastName
  }
}

// Then this query can be read completely from cache
{
  user(id: 5) {
    firstName
  }
}

// But this one will refetch all of the fields
{
  user(id: 5) {
    firstName
    middleName
    lastName
  }
}
```

At the top of my list is to better document the cache format so that external utilities can be written against it.

#### Conclusion

Given that our goals are so similar with these tools, I feel like a deeper collaboration would benefit everyone. At the very least, we should see what we can share in terms of design - I'll take a deeper look at Relate tonight to see what it does under the hood.

Like I said, I'm not super opinionated so if there are places we disagree we could just make that pluggable -- it would be great if we could at least share a lot of the underlying utilities and Redux actions, so that people could build plugins for pagination, etc. that would work with both clients.

**Comment by bruno12mota** [comment]
Collaborating on this would be awesome @stubailo. Relate's code could be better organized, I started it in Relax itself as a proof of concept then since I think I was achieving something that could work I switched it to a separate repo.

Basically Relate has three main concepts/ideas behind it:

* Normalization by ids - any data that comes from queries are normalized and put in a key value store http://relax.github.io/relate/how-it-works.html
* Components (or data connectors in Relate terms) should get the data they asked for, and update when some node they're listening to changes
* Queries should be bundled and requested in one go, even when requesting same resource with different variables for different data connectors

Normalization by ids works really well, so it's something you guys should definitely look into next.

### Caching

I still didn't make caching for Relate, although my vision for it would be using the id normalization result. Which is a different approach from what you've done. For example:

If there is a query for:

```js
pages {
  _id
  title
}
```

And the result retrieved from the server would be:

```js
{
  pages: [
    {_id: 'a', title: 'A'},
    {_id: 'b', title: 'B'}
  ]
}
```

The normalized store would have:

```js
{
   a: {_id: 'a', title: 'A'},
   b: {_id: 'b', title: 'B'}
}
```

And the cache store would have:

```js
{
   pages: ['a', 'b']
}
```

This is a pretty simple example but I think you get my point. This is what I do in Relate for the connectors store already. In the connectors store I'd have something like:

```js
{
  [connectorID]: {
    data: {pages: ['a', 'b']}
    listens: ['a', 'b']
  }
}
```

The data that goes into the redux relate reducer is the result of processing the connector's data. And that listens array serves to indicate all nodes that the connector is listening to. So if there is a mutation somewhere in the app to the node 'b', this connector would update.

With this you can also check which fields where already fetch for a query, which would solve the problem you mentioned above.

### JSON vs strings queries

I've found it really cool to be able to work with objects on this. Although I totally get your points. I think the best solution would be enabling both. Although I think strings should be only used for fragments. Variables are definitely better set as json, for example:

```js
{
      fragments: Media.fragments,
      variablesTypes: {
        media: {
          sort: 'String',
          order: 'String',
          search: 'String',
          s: 'String',
          filters: '[Filter]'
        }
      },
      initialVariables: {
        media: {
          sort: props.sort,
          order: props.order,
          search: 'name',
          s: props.search,
          filters
        }
      }
}
```

So I don't have to worry about variables namespacing or colliding with other queries from other components that will be merged here. Relate does that for you. And since I've already defined the variables types, to make a new query with new variables you just have to do:

```js
relate.setVariables({
   media: {
      sort: nextProps.sort,
      order: nextProps.order,
      search: 'name',
      s: : nextProps.search
    }
});
```

This is in my opinion a good abstraction to have. As to defining fragments as strings, completely not opposed to it as setting them as json is not the brightest way. So, in conclusion I think a cool way to do this would be to have the template literal tag return a json with the same format. So that:

```js
static fragments = ql`
  pages {
    _id
    title
  }
`
``` 

would be equal to

```js
static fragments = {
  pages: {
    _id: 1,
    title: 1
  }
}
```

So user could choose which to use. Let me know your thoughts on this.

I think we should definitely collaborate on it. Relate is quite restrict to a specific tech stack since I've made it for Relax in specific, so Apollo is much more wide usable. I don't mind at all sharing my ideas with you guys, you're quite ahead of me on this 😄 

Wouldn't say merge the projects, at least for now, since I think Apollo is missing some features Relax definitely needs which I prioritized on Relate over others you guys already have. But would be great to reach a final project and sort of unite the best of both.

Cheers!

**Comment by stubailo** [comment]
Hey sounds like one option could be to wait until Apollo Client has the right features, then I can put in a PR for it. Sounds like the blockers are:

1. Normalization by IDs - this is [already built into Apollo Client](https://github.com/apollostack/apollo-client/blob/7e83e649a8baa7df595a46c12699774ac35aab2c/test/writeToStore.ts#L147-L186), it just isn't in the public API yet. We want to make normalization pluggable, so it's just a matter of saying "the ID field is the special one".
2. Batching queries across different UI components - we have an [issue open for this](https://github.com/apollostack/apollo-client/issues/25), but it seems like it would be largely fixed by server rendering and store hydration, no?
3. Query composition via fragments, where the fragments have variables attached that are incorporated into the larger query.

> So I don't have to worry about variables namespacing or colliding with other queries from other components that will be merged here. Relate does that for you. 

Are you referring to merging fragment variables into the larger query here? GraphQL doesn't have a syntax for fragment variables, so until it does perhaps JSON is the best way.

> And since I've already defined the variables types, to make a new query with new variables you just have to do:

Apollo also has `refetch(variables)` on the query subscription, so you can do a similar thing.

------

Sounds like these things are pretty similar - I'll let you know when all of the concerns you're talking about are addressed, they sound like really useful features to have!

> I think we should definitely collaborate on it. Relate is quite restrict to a specific tech stack since I've made it for Relax in specific, so Apollo is much more wide usable. I don't mind at all sharing my ideas with you guys, you're quite ahead of me on this

Would it be OK if I ping you on various design discussions as we are building these features?

Awesome stuff!

**Comment by bruno12mota** [comment]
Of course, I'll be more than glad to help and possibly contribute. I'll have to do some work on Relate as well though since I'm using it another project as well. 

Batching queries is definitely important, not only on server side. Otherwise it's ignoring the advantage of having GraphQL in the first place. When components are requesting the same thing with different variables what I've done was namespacing the query. For example if two comp want pages with different variables it should make a query like the following:

```
pages (...) {}
relate_0: pages (...) {}
```

I have some extra concerns that I don't know how you guys handle in Apollo that proved to be really helpful in Relate, for example, do you guys listen for mutations on data connectors.

In Relate if a data connector asks for a list of pages for example, I needed a way to when a new page is added from some mutation, it would be added to the list in that data connector. Thus the mutation property on the data conectors settings http://relax.github.io/relate/data-connect.html. With this you can also specify an order, and ideally you should even be able to sort it in between.

I do see you guys also have mutate action http://docs.apollostack.com/apollo-client/core.html#mutate. Quite similar to relate.

I'll look in more detail to Apollo and the code itself when I get some time and see where I can contribute or help 😄

**Comment by stubailo** [comment]
Thanks! I can see that you have some optimizations we don't have yet, but hopefully those are easy to solve!

> I needed a way to when a new page is added from some mutation

Can you give me an example of this? Is this purely for optimistic UI handling? or does it inform how the data is refetched/integrated into the store?

**Comment by bruno12mota** [comment]
@stubailo not about optimistic ui but or refetching data. In another place of your app you might trigger an action to add a new page that should be added to another component's pages list. For example, in Relax I have the pages list container with this config:

```js
{
    fragments: Menu.fragments,
    variablesTypes: {
      pages: {
        sort: 'String',
        order: 'String',
        search: 'String',
        s: 'String'
      }
    },
    initialVariables: {
      pages: {
        sort: props.sort,
        order: props.order,
        search: 'title',
        s: props.search
      }
    },
    mutations: {
      addPage: [
        {
          type: 'PREPEND',
          field: 'pages'
        }
      ]
    }
  }
```

What that last mutations config does is defining that when an addPage mutation occurs somewhere, the resulting page should be added to this connector's pages list. This has been working quite well for me on Relax. So not how it is integrated into the store, but into the connectors store.

**Comment by stubailo** [comment]
Oh, OK I understand now. Basically, when a new page is added, you need to:

1. Load the data for the new page, and
2. Make sure that page is appended to any relevant arrays on the client

So for (1) you use the mutation refetch, and for (2) you have a special field on the fragment.

Very interesting and practical solution, that means you don't need to refetch the list itself to figure out the position of the new item, if you already know what it should be on the client. Definitely something to keep in mind.

I was thinking of something like refetching the `id` fields of the items in the list, to have the order fix itself.

Do you find yourself sorting data on the client, or relying on the sort order returned by the GraphQL server?

As a side note, similar stuff is necessary for optimistic UI updates, which is another thing Relay uses these for I believe.

**Comment by bruno12mota** [comment]
Here's an example of it on Relax. I perform a redux action to add the new page https://github.com/relax/relax/blob/master/lib/shared/actions/page.js#L143 and on the pages list I set what to do when that mutation return https://github.com/relax/relax/blob/master/lib/shared/screens/admin/screens/pages/menu.js#L38

This has being proven to be really cool. It's up to the connector to now if it should be appended or prepended in the list. For now there's no way to put it somewhere in the middle. But I think that could also be achieved in a similar way.

And yes I don't refetch the list  to check the order. Even with ids only I think it's not ideal.

Also I do rely on the sort order coming from graphql, future mutations that add nodes to the lists are a responsibility of the connector to put where it wants.

Optimistic UI wasn't really a big concern for me, since I think that can be handled in redux itself.

**Comment by smolinari** [comment]
I'd like to chime in here if I may. Either I'll be showing my ignorance or some insight as "the end user". 

Although I would agree a client-side update of, I'll call it "secondary data from a primary query/ mutation", may seem like it comes in handy in many situations, to me it means the client is way, way too smart. The fact one set of data relates to another in any way is very, very intimate knowledge of the data itself and, I believe that blows by GraphQL's intentions. Yes, you could say, this extends GraphQL, but is it really necessary at all? 

When I read your post Bruno, I asked myself, what is this method of secondary data updates improving? What problem is it solving? In your example, if I understand it correctly, if I go to the list of articles page, my saved article is already in the list of articles, somewhere. Though, I'd really still want to have the server queried for the proper list. I'd want this because, there might be other authors entering in articles, which I (the client) don't know about.  

To through in an idea, [in the discussion about streaming data](https://github.com/apollostack/apollo-client/issues/180), I see that as the future to have secondary updates. It just has to be done smartly, because, if you have a really big application, it certainly shouldn't be pushing every update to every client. :smile: 

Sashko - maybe that is why FB didn't go that route either (or rather yet). :wink:  

Scott

**Comment by bruno12mota** [comment]
Hey @smolinari don't think you quite understood it. 

Relate assumes nothing, so it is quite of dumb really. I think you misunderstood one core concept of Relate, which is that data is relative to each connector. So what I implemented is a way for a connector to listen for a given mutation and add the result to a list, without having to refetch the entire list due to an insertion. Of course, if the user navigates out of that connector and in again, it will fetch the list again. There's no smart caching or intelligence there 😛

**Comment by bruno12mota** [comment]
@stubailo have you guys done/thought about server side rendering? More in specific for React. Been trying to come up with a clever and efficient way to do it but not seeing a lot of choices: https://github.com/facebook/react/issues/1739

**Comment by smolinari** [comment]
I doubt highly you'll change Relax just because of this one feature and this is sort of off-topic (sorry), but it seems SSR might be React's Achilles heel. So, I'd just like to throw in the fact that [Vue.js 2.0 is going to include SSR](https://github.com/vuejs/vue/issues/2873). And when that happens, I believe Vue will take off like a rocket and I hope (and would guess) it will get a lot more love from the GraphQL community too. :smile:

Scott

**Comment by bruno12mota** [comment]
Vue seems to be quite similar to Angular no? Nevertheless in React you can also have a good SSR, check this talk for example https://www.youtube.com/watch?feature=player_embedded&v=PnpfGy7q96U

The most interesting thing there is caching at a component level, which I think is an awesome approach. This talk is really spot on in referring all the aspects of SSR in React and how react team don't seem to give it much attention. I might get my hands dirty on React as well, we'll see. I'll leave this issue for a bit further ahead but it's definitely something that concerns me

**Comment by bruno12mota** [comment]
@smolinari following in #247

**Comment by stubailo** [comment]
@bruno12mota hey, just came back from a long vacation! We're trying to implement a very easy solution for SSR in React.

We've got some initial PRs with very basic tests here: https://github.com/apollostack/react-apollo/pull/75

I don't think we are going to have any solutions for actually reducing the CPU load of the HTML rendering, for now we are just addressing the blockers for getting the data in. We're also interested in having really good store hydration, which can be a great approach where SSR isn't an option.

@tmeasday is working on a boilerplate for Apollo with SSR built in, maybe he can chime in.

**Comment by bruno12mota** [comment]
Hey @stubailo! Don't you guys have a way to define data dependencies on a component level? How do you guys statically fetch those data requirements?

For relate I've made a function that traverses the components tree, like in React but with no markup being generated, and gather the data dependencies for that specific route. https://github.com/relax/relate/blob/master/lib/server/get-data-dependencies.js

So it gets quite simple to fetch it after: https://github.com/relax/relax/blob/master/lib/server/routers/admin.js#L72

Was quite tricky to make, it cannot be statically analyzed since data dependencies depend on props and router state. Just wondering what is your approach for this.

**Comment by stubailo** [comment]
> Don't you guys have a way to define data dependencies on a component level? How do you guys statically fetch those data requirements?

We are currently working on this, I think one approach is to just render the tree twice, once to get the queries and a second time with the actual data. I think static analysis is too restricting because then you limit what people can do with the queries. We'll see if it works out - I'll definitely let you know.

**Comment by bruno12mota** [comment]
Well, that's what I've done in Relate. But I didn't want to use the react render method to not generate unnecessary markup which would degrade performance a lot so I made my own simple render method, you guys can take a look to it and even reuse the code if you want (still need to make some unit tests for it but is working great on Relax)

**Comment by stubailo** [comment]
That sounds like a great idea! I was thinking we could avoid rendering any children of the GraphQL container components, which would probably reduce rendering burden by a lot!
