### ISSUE TITLE
npm start: NODE_ENV=production ./node_modules/.bin/babel-node app

### ISSUE THREAD

**Issue by jonas2** [relax/relax#231]
Cannot start a fresh clone of git repository. Any suggestions?

**System:** 
MacOSX El Capitan, Node 6.0.0

**Error on "npm start":**
Johannes-IT-Center-MacBook-Pro:relax hannes$ npm start

> relax@0.0.0 start /Users/hannes/Desktop/relax
> NODE_ENV=production ./node_modules/.bin/babel-node app

sh: ./node_modules/.bin/babel-node: No such file or directory

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/hannes/.nvm/versions/node/v6.0.0/bin/node" "/Users/hannes/.nvm/versions/node/v6.0.0/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! relax@0.0.0 start: `NODE_ENV=production ./node_modules/.bin/babel-node app`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the relax@0.0.0 start script 'NODE_ENV=production ./node_modules/.bin/babel-node app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the relax package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production ./node_modules/.bin/babel-node app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs relax
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls relax
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hannes/Desktop/relax/npm-debug.log

**Comment by bruno12mota** [comment]
`npm start` is currently buggy on master. Use `npm run dev` only for now

**Comment by jonjaques** [comment]
@jonas2 Maybe try pulling one more time? @bruno12mota my apologies, I missed this in my PR summary; but in b737548 also changed `npm start` to use the webpack.node build instead of using babel-node. My reasoning for this was since babel-node is [discouraged](https://babeljs.io/docs/usage/cli/) in production. Also AFAIK since we define babel args inside the webpack config; babel-node@6 would complain anyways, since it has no way of knowing which presets/plugins to use.

**Comment by bruno12mota** [comment]
@jonjaques I saw it 😃  

Ideally we wouldn't need the `.babelrc` since it would mean having duplicate configuration. I haven't updated the production build process for quite a while, so that build didn't reflect the current setup. The idea would be having webpack build it as well. 

This area needs some work on it still, since the master is still in dev only state I haven't picked this up.

**Comment by jonjaques** [comment]
@jonas2 @bruno12mota, this should be fixed with #236

**Comment by bruno12mota** [comment]
👍  closing until notice in contrary
