### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by n3v3rf411** [relax/relax#247]
Hi!

I've just cloned and built the latest source from master and couldn't get server-side rendering to work in both dev and production builds. Every time I navigate to /admin/colors, graphql is called from the browser - not from the server.

I'm planning to use relate-js in my project and follow how it's used in relax but also couldn't get server-side rendering to work though it does from the relax demo site. I even checked out an old commit (609ee5e) but the result is still the same.

Thanks in advance!

**Comment by bruno12mota** [comment]
Hey! The server side rendering is broken since a refactor a couple of months ago. Will work on that after completing a few more things. If someone wants to pick that up sooner would be great 😄 

Since we're now using Relate, it will probably need to render once to see the data the components need, then fetch the data and re render with the hydrated store. This is also not yet ready on Relate, it should be simple though. When rendering server side, Relate should store the data needs in redux, then it's a matter of pulling that and make the query.

**Comment by jonjaques** [comment]
@bruno12mota checkout redux-connect - 
https://github.com/makeomatic/redux-connect/blob/master/modules/components/AsyncConnect.js

Basically this provides the react-router integration and handles container dependencies. I think this could be integrated into Relate. (Disclaimer, I have not looked at relate - but as I understand is roughly equivalent to react-redux@connect)

However, would need to do some refactoring on your screens (again, cursory look at the codebase) - so in your top level components, you would want to build up an array of dispatches which would describe the data you need to load a particular screen. 

```
@asyncConnect([
  { key: 'colors', promise: ({ getState, dispatch, params })=> {
    if (!getState().colors.loaded) {
      return dispatch(loadColors())
    }
    return Promise.resolve(null)
  }}
])
```

Quick dirty example, but you get the idea. This will fire on the server, but not on the client because state is already populated. However, if user navigates from diff page it would fire on client.

I don't know what implications this has for graphql queries, as I am still trying to learn in that area. :smile:

**Comment by bruno12mota** [comment]
@jonjaques yes the solution would be similar with Relate. Although, to know the data dependencies it would need to render once, on which data needed would be added to the redux store. Then it's a matter of fetching that data and re render with it by hydrating relate's store beforehand. The problem is I can't see a way without having the two renders but maybe this can be done in a performant way.

I believe Relay's server side rendering works pretty much like this.

**Comment by jonjaques** [comment]
In your container components, how do they *currently* know which data they need? When in the rendering lifecycle does it fire off actions?

The approach above (`@asyncConnect`) works because it's statically describing the data dependencies for a particular component. So we can dispatch actions without having to instantiate a component (avoids double render).

**Comment by bruno12mota** [comment]
Relate has two connectors:

* data connectors - they specify the data they need, and call a fetchData function on the constructor.
* root data connector - this will receive all fetchData calls, and bundle them in a single query

The result of the bundle can be saved and queried on the server side. But after getting the data, a new render is needed. So, Relate can't make a static evaluation of the data needs because each container is not aware of their children's containers data needs

**Comment by bruno12mota** [comment]
Been making some experimentation which is turning out good. Made a renderer for Relate that goes through the components tree and catches the data dependencies. Looking pretty good, made a benchmark for it and the results are not bad at all:

![screen shot 2016-06-10 at 4 40 15 pm](https://cloud.githubusercontent.com/assets/4086031/15968480/5dfcb584-2f2c-11e6-8912-53784c9d5252.png)

The result from the render outputs a 1MB minified html so the results are not bad. Will lime this a bit further and apply it to relate.
