### ISSUE TITLE
Startup yarn error. 

### ISSUE THREAD

**Issue by krizka** [relax/relax#417]
After cloning repo and doing yarn, i got:
```
relax $ yarn
relax $ yarn build
yarn build v0.15.1
$ "cross-env NODE_ENV=production webpack --config ./webpack/prod/webpack.config.js"
sh: cross-env NODE_ENV=production webpack --config ./webpack/prod/webpack.config.js: No such file or directory
error Command failed with exit code 127.
info Visit http://yarnpkg.com/en/docs/cli/build for documentation about this command.```
what am I doing wrong?

**Comment by searsaw** [comment]
First, I'd try updating `yarn` since you're using a very old version. As of this writing, `0.19.1` is the most up-to-date. Next, check to make sure that the `yarn` call actually worked. If nothing was outputted after you ran `yarn` like it shows above, then I don't think the installation succeeded. If you're behind a proxy, you will want to make sure `http_proxy` and `https_proxy` are set to make sure you can install the dependencies.

Also, if you're on a Windows machine instead of Linux or Mac, then the path `./webpack/prod/webpack.config.js` may not work. You would need to give it a path that works on Windows. Im not sure on that last point. I haven't used a Windows machine in ages. :)

**Comment by krizka** [comment]
Thanks, you are right, yarn upgrade helped.
