### ISSUE TITLE
Remove Nucleo icons

### ISSUE THREAD

**Issue by sebastiano-guerriero** [relax/relax#428]
This repository includes our Nucleo icons. That is against our terms https://nucleoapp.com/license/

Nucleo is a premium icon pack, and you're redistributing the icon font version for free. That clearly is not allowed, therefore it needs to be removed immediately.

**Comment by bruno12mota** [comment]
Hi Sebastiano,

With all due respect my interpretation was another. We're not redistributing Nucleo, but using it on a single application/product that is Relax. Yes we have the web font file in our repo, because it's an open source project, but if other users will use it for their own projects, they're the ones violating the license. And let's be real in saying that any application using nucleo's icon font version, you can easily get the source file from the network, so don't see a difference.

We didn't do that of course and bought a license from you guys, it's an awesome product and would be a shame to raise an issue here.

**Comment by sebastiano-guerriero** [comment]
From our license:

"You don't have the right to:

Sublicense, resell, share, transfer, or otherwise redistribute Nucleo icons on its own (even for free)."

There's no room for interpretation. It's our icon set packed and redistributed, plain and simple.

**Comment by bruno12mota** [comment]
But you do have the notion I can just go to a website that is using the nucleo's web font and just get it from there? How is that different? I'm not redistributing Nucleo icons on its own, it's part of an application that happens to be open source. Also note we don't allow its use on the CMS itself.

**Comment by sebastiano-guerriero** [comment]
Bruno, you do understand that having a zipped file containing a copyrighted product on a public repository is not allowed? Our members can use our icon font to import the icons in Photoshop.

You're basically saying: why can't I infringe your terms if other people can do the same? A user could download all our icons in a different vector format and give them away for free. Would that give you the right to do the same?

I'm asking to have respect for the work of other people that put a lot of effort in what they do. Either that or I'll get in touch with the legal department of Github to put down this repo.

**Comment by 4levels** [comment]
Hi @sebastiano-guerriero,

Can you explain how one can
(from your license)
> Use Nucleo icons in unlimited personal and commercial projects.

without using the font file and including it in this repo?

I'm no licensing expert, but your licensing terms seem to be contradictive.  Can you please provide instructions on how to use Nucleo's icons in the context of this project?

Besides that I'm sure the good people of this project have no intention to infringe your license, use your icons in an unfair manner or do you any harm.  In fact, from @bruno12mota's reply I can clearly deduct that they support your project..

On a general note: this issue tracker is for code issues and people actually using relax, not complaints over licenses or any other non development related things.  I suggest this ticket should be closed and Nucleo should contact you properly.

@bruno12mota, if using Nucleo's icons will cause trouble, I'm sure they can easily be swapped with a friendlier icon provider that doesn't start threatening with legal blabber to put down this repo, right?  For me, Sebastiano's attitude has already made me dislike Nucleo a lot and I will never ever use it in any of my projects.

**Comment by bruno12mota** [comment]
I'll remove it don't worry. Just really let down on how you handled this and this policy which I cannot understand. I do respect your work, and that's not what I'm saying at all. What I'm saying is that if anyone wanted to use nucleo for free and get exactly these files, they could perfectly get them with the most ease from a "non infringing" website by just getting them in the network panel of dev tools. It's almost easier than how it is here on Relax because you don't even have to search.

Anyway, will remove it asap and link the commit here. Just on a side note, you could perfectly have joined us as a "sponsor" and get some advertisement out of it, instead of this.

Was a shame to meet you Sebastiano, actually had a lot of respect for you guys, you have a legit product. Treating your customers like this, specially on an open source project is a real let down.

**Comment by sebastiano-guerriero** [comment]
https://github.com/relax/relax/tree/optimize-page-renderer/assets/fonts

https://github.com/relax/relax/tree/feature/55/assets/fonts

**Comment by bruno12mota** [comment]
Thanks @4levels! No point in arguing, it is what it is.

Sebastiano, removed the optimize-page-renderer branch, which was one of my branches. Can't remove/control the others.

**Comment by bruno12mota** [comment]
Loosing clients already Sebastiano https://github.com/relax/relax/issues/396 👍

**Comment by jiri** [comment]
I'll add my two cents here because it seems prudent -- I stumbled upon this issue while researching whether Nucleo icons have an icon I want, since the website makes it impossible to search the icons (which is a little silly in itself).

Seeing how @sebastiano-guerriero handled this issue made me decide to not use it solely because I don't need this kind of hassle. I fail to see how accessing a web font file from a hosted website is in any way different from accessing the font from a hosted copy of the source (because it's not) and your failure to even address this point is jarring. At the very least it points to an acute lack of any technical knowledge, which could be excused from a designer, were it not for the overtly arrogant tone of your replies.
