### ISSUE TITLE
Preview mode is being persisted after leaving a page

### ISSUE THREAD

**Issue by magalhas** [relax/relax#49]
It's annoying. We also need a way to quickly distinguish preview mode from editing mode. Hide all the chrome and keep a "end preview" button somewhere?

**Comment by bruno12mota** [comment]
Just have to do the latter, it implies that preview mode isn't 'persisted ' changing page

**Comment by magalhas** [comment]
As long as you don't hit the back button on the browser or close the tab and come back later. So, "persisting" it somewhere else is needed, right?

**Comment by bruno12mota** [comment]
Right, it should come out of preview when hitting the back button for example

**Comment by ivomiguelas2** [comment]
Having the chrome disappear would remove the need to publish in order to see it as the final outcome. This is where keyboard shortcuts will be an extremely useful and expected way to leave the state. They should never be the only way to perform an action, but allow the opportunity to minimise the UI.

**Comment by bruno12mota** [comment]
Done from the refactor
